import type { ResumeData, TemplateId } from '../types'
const has=(value:unknown)=>Array.isArray(value)?value.some(Boolean):!!String(value??'').trim()
const lines=(value:string)=>value.split(/\n|;/).map(x=>x.replace(/^[-]\s*/, '').trim()).filter(Boolean)
const Link=({value,label}:{value:string;label?:string})=>value?<a href={/^https?:/.test(value)?value:`https://${value}`} target="_blank" rel="noreferrer">{label||value}</a>:null
const profileUrl=(value:string,platform:'linkedin'|'github'|'portfolio')=>{
  const clean=value.trim().replace(/^@/,'')
  if(/^https?:\/\//i.test(clean))return clean
  if(clean.includes('.'))return `https://${clean}`
  if(platform==='github')return `https://github.com/${clean}`
  if(platform==='linkedin')return `https://linkedin.com/in/${clean}`
  return `https://${clean}`
}
const ProfileLink=({value,platform}:{value:string;platform:'linkedin'|'github'|'portfolio'})=>value?<a href={profileUrl(value,platform)} target="_blank" rel="noreferrer">{value}</a>:null
const Heading=({children}:{children:React.ReactNode})=><h3 className="resume-heading">{children}</h3>
function Experience({data}:{data:ResumeData}){const entries=data.experiences.filter(e=>has(e.company)||has(e.role)||has(e.description));if(!entries.length)return null;return <section><Heading>Experience</Heading>{entries.map(e=><article className="resume-entry" key={e.id}><div className="entry-head"><div><strong>{e.role}</strong>{e.company&&<span> - {e.company}</span>}</div><span>{[e.startDate,e.endDate].filter(Boolean).join(' to ')}</span></div>{e.location&&<em>{e.location}</em>}{lines(e.description).length>0&&<ul>{lines(e.description).map((b,i)=><li key={i}>{b}</li>)}</ul>}</article>)}</section>}
function Projects({data}:{data:ResumeData}){const entries=data.projects.filter(p=>has(p.name)||has(p.description)||has(p.techStack));if(!entries.length)return null;return <section><Heading>Projects</Heading>{entries.map(p=><article className="resume-entry" key={p.id}><div className="entry-head"><strong>{p.name}</strong><span>{p.techStack}</span></div>{lines(p.description).length>0&&<ul>{lines(p.description).map((b,i)=><li key={i}>{b}</li>)}</ul>}<div className="resume-links"><Link value={p.githubLink} label="GitHub"/><Link value={p.liveLink} label="Live project"/></div></article>)}</section>}
function Education({data}:{data:ResumeData}){const entries=data.education.filter(e=>has(e.institution)||has(e.degree)||has(e.field));if(!entries.length)return null;return <section><Heading>Education</Heading>{entries.map(e=><article className="resume-entry compact" key={e.id}><div className="entry-head"><strong>{e.institution}</strong><span>{[e.startYear,e.endYear].filter(Boolean).join(' to ')}</span></div><div>{[e.degree,e.field].filter(Boolean).join(', ')}{e.score&&` - ${e.score}`}</div></article>)}</section>}
function Certifications({data}:{data:ResumeData}){const entries=data.certifications.filter(c=>has(c.name)||has(c.organization));if(!entries.length)return null;return <section><Heading>Certifications</Heading>{entries.map(c=><div className="compact-row" key={c.id}><span><Link value={c.link} label={c.name}/>{!c.link&&c.name}{c.organization&&` - ${c.organization}`}</span><span>{c.year}</span></div>)}</section>}
const Contact=({data}:{data:ResumeData})=><div className="resume-contact">{data.personal.email&&<a href={`mailto:${data.personal.email}`}>{data.personal.email}</a>}{data.personal.phone&&<span>{data.personal.phone}</span>}{data.personal.location&&<span>{data.personal.location}</span>}<ProfileLink value={data.personal.linkedIn} platform="linkedin"/><ProfileLink value={data.personal.github} platform="github"/><ProfileLink value={data.personal.portfolio} platform="portfolio"/></div>
const Skills=({data}:{data:ResumeData})=>has(data.skills)?<section><Heading>Skills</Heading><div className="skill-list">{data.skills.filter(Boolean).map((s,i)=><span key={`${s}-${i}`}>{s}</span>)}</div></section>:null
const Extra=({data}:{data:ResumeData})=><>{has(data.achievements)&&<section><Heading>Achievements</Heading><ul>{data.achievements.filter(Boolean).map((x,i)=><li key={i}>{x}</li>)}</ul></section>}{has(data.languages)&&<section><Heading>Languages</Heading><div>{data.languages.filter(Boolean).join(' / ')}</div></section>}</>
const Summary=({data}:{data:ResumeData})=>has(data.summary)?<section><Heading>Professional Summary</Heading><p>{data.summary}</p></section>:null
export default function Preview({data,template}:{data:ResumeData;template:TemplateId}){const p=data.personal
  if(template==='classic-ats')return <div className="resume-page classic"><header><h1>{p.fullName||'Your Name'}</h1>{p.jobTitle&&<h2>{p.jobTitle}</h2>}<Contact data={data}/></header><Summary data={data}/><Skills data={data}/><Experience data={data}/><Projects data={data}/><Education data={data}/><Certifications data={data}/><Extra data={data}/></div>
  if(template==='modern-professional')return <div className="resume-page modern"><aside><div className="identity"><h1>{p.fullName||'Your Name'}</h1><h2>{p.jobTitle}</h2></div><Contact data={data}/><Skills data={data}/><Education data={data}/><Certifications data={data}/><Extra data={data}/></aside><main><Summary data={data}/><Experience data={data}/><Projects data={data}/></main></div>
  return <div className="resume-page creative"><header><div className="initials">{(p.fullName||'YN').split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase()}</div><div><h1>{p.fullName||'Your Name'}</h1><h2>{p.jobTitle}</h2></div><Contact data={data}/></header><div className="creative-body"><aside><Skills data={data}/><Education data={data}/><Certifications data={data}/><Extra data={data}/></aside><main><Summary data={data}/><Experience data={data}/><Projects data={data}/></main></div></div>
}
