import { useRef, useState } from 'react'
import html2pdf from 'html2pdf.js'
import Preview from './Preview'
import { createId } from '../data/resume'
import type { Certification, Education, Experience, Project, ResumeData, TemplateId } from '../types'

const Field=({label,value,onChange,type='text',placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string})=><label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>
const TextArea=({label,value,onChange,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string})=><label className="field full"><span>{label}</span><textarea value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>
const Section=({title,children,onAdd}:{title:string;children:React.ReactNode;onAdd?:()=>void})=><section className="editor-section"><div className="editor-section-head"><h3>{title}</h3>{onAdd&&<button className="small-btn" onClick={onAdd}>+ Add</button>}</div>{children}</section>
const Remove=({onClick}:{onClick:()=>void})=><button className="remove-btn" onClick={onClick} aria-label="Remove item">Remove</button>

export default function ResumeBuilder({data,onChange,template,onLoadSample}:{data:ResumeData;onChange:(d:ResumeData)=>void;template:TemplateId;onLoadSample:()=>void}){
  const [collapsed,setCollapsed]=useState(false), previewRef=useRef<HTMLDivElement>(null)
  const setPersonal=(key:keyof ResumeData['personal'],value:string)=>onChange({...data,personal:{...data.personal,[key]:value}})
  const updateList=<T extends {id:string}>(key:'experiences'|'projects'|'education'|'certifications',id:string,field:keyof T,value:string)=>onChange({...data,[key]:(data[key] as T[]).map(x=>x.id===id?{...x,[field]:value}:x)})
  const removeList=(key:'experiences'|'projects'|'education'|'certifications',id:string)=>onChange({...data,[key]:data[key].filter(x=>x.id!==id) as never})
  const exportPdf=async()=>{if(!previewRef.current)return;await html2pdf().set({margin:0,filename:`${data.personal.fullName||'resume'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff'},jsPDF:{unit:'in',format:'a4',orientation:'portrait'},pagebreak:{mode:['avoid-all','css','legacy']}}).from(previewRef.current).save()}
  const setStringList=(key:'skills'|'achievements'|'languages',index:number,value:string)=>{const list=[...data[key]];list[index]=value;onChange({...data,[key]:list})}
  const addString=(key:'skills'|'achievements'|'languages')=>onChange({...data,[key]:[...data[key],'']})
  const removeString=(key:'skills'|'achievements'|'languages',i:number)=>onChange({...data,[key]:data[key].filter((_,n)=>n!==i)})
  return <section className="builder"><div className="builder-toolbar"><div><span className="eyebrow">Resume studio</span><h2>Complete resume editor</h2></div><div className="button-row"><button className="btn ghost" onClick={onLoadSample}>Load sample resume</button><button className="btn ghost" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'Expand':'Collapse'}</button><button className="btn" onClick={exportPdf}>Export PDF</button></div></div>
    <div className={`builder-grid ${collapsed?'editor-collapsed':''}`}>
      {!collapsed&&<div className="editor glass-card">
        <Section title="Personal details"><div className="field-grid">{([
          ['fullName','Full Name'],['jobTitle','Job Title'],['email','Email'],['phone','Phone'],['location','Location'],['linkedIn','LinkedIn'],['github','GitHub'],['portfolio','Portfolio']
        ] as [keyof ResumeData['personal'],string][]).map(([k,l])=><Field key={k} label={l} value={data.personal[k]} onChange={v=>setPersonal(k,v)}/>)}</div></Section>
        <Section title="Professional summary"><TextArea label="Summary" value={data.summary} onChange={v=>onChange({...data,summary:v})} placeholder="Tell recruiters what you do, your strengths, and the impact you create."/></Section>
        <Section title="Skills" onAdd={()=>addString('skills')}><p className="helper">Paste comma-separated skills into any field to add several at once.</p><div className="tag-editor">{data.skills.map((s,i)=><div className="inline-item" key={i}><input value={s} placeholder="e.g. TypeScript" onChange={e=>{const parts=e.target.value.split(',');if(parts.length>1){const copy=[...data.skills];copy.splice(i,1,...parts.map(x=>x.trim()).filter(Boolean));onChange({...data,skills:copy})}else setStringList('skills',i,e.target.value)}}/><Remove onClick={()=>removeString('skills',i)}/></div>)}</div></Section>
        <Section title="Experience" onAdd={()=>onChange({...data,experiences:[...data.experiences,{id:createId(),company:'',role:'',location:'',startDate:'',endDate:'',description:''}]})}>{data.experiences.map(x=><div className="repeat-card" key={x.id}><Remove onClick={()=>removeList('experiences',x.id)}/><div className="field-grid"><Field label="Company" value={x.company} onChange={v=>updateList<Experience>('experiences',x.id,'company',v)}/><Field label="Role" value={x.role} onChange={v=>updateList<Experience>('experiences',x.id,'role',v)}/><Field label="Location" value={x.location} onChange={v=>updateList<Experience>('experiences',x.id,'location',v)}/><Field label="Start Date" value={x.startDate} onChange={v=>updateList<Experience>('experiences',x.id,'startDate',v)}/><Field label="End Date" value={x.endDate} onChange={v=>updateList<Experience>('experiences',x.id,'endDate',v)}/><TextArea label="Description / bullet points" value={x.description} onChange={v=>updateList<Experience>('experiences',x.id,'description',v)} placeholder="One achievement per line"/></div></div>)}</Section>
        <Section title="Projects" onAdd={()=>onChange({...data,projects:[...data.projects,{id:createId(),name:'',techStack:'',description:'',githubLink:'',liveLink:''}]})}>{data.projects.map(x=><div className="repeat-card" key={x.id}><Remove onClick={()=>removeList('projects',x.id)}/><div className="field-grid"><Field label="Project Name" value={x.name} onChange={v=>updateList<Project>('projects',x.id,'name',v)}/><Field label="Tech Stack" value={x.techStack} onChange={v=>updateList<Project>('projects',x.id,'techStack',v)}/><Field label="GitHub Link" value={x.githubLink} onChange={v=>updateList<Project>('projects',x.id,'githubLink',v)}/><Field label="Live Link" value={x.liveLink} onChange={v=>updateList<Project>('projects',x.id,'liveLink',v)}/><TextArea label="Description / bullet points" value={x.description} onChange={v=>updateList<Project>('projects',x.id,'description',v)}/></div></div>)}</Section>
        <Section title="Education" onAdd={()=>onChange({...data,education:[...data.education,{id:createId(),institution:'',degree:'',field:'',startYear:'',endYear:'',score:''}]})}>{data.education.map(x=><div className="repeat-card" key={x.id}><Remove onClick={()=>removeList('education',x.id)}/><div className="field-grid"><Field label="Institution" value={x.institution} onChange={v=>updateList<Education>('education',x.id,'institution',v)}/><Field label="Degree" value={x.degree} onChange={v=>updateList<Education>('education',x.id,'degree',v)}/><Field label="Branch / Field" value={x.field} onChange={v=>updateList<Education>('education',x.id,'field',v)}/><Field label="Start Year" value={x.startYear} onChange={v=>updateList<Education>('education',x.id,'startYear',v)}/><Field label="End Year" value={x.endYear} onChange={v=>updateList<Education>('education',x.id,'endYear',v)}/><Field label="CGPA / Percentage" value={x.score} onChange={v=>updateList<Education>('education',x.id,'score',v)}/></div></div>)}</Section>
        <Section title="Certifications" onAdd={()=>onChange({...data,certifications:[...data.certifications,{id:createId(),name:'',organization:'',year:'',link:''}]})}>{data.certifications.map(x=><div className="repeat-card" key={x.id}><Remove onClick={()=>removeList('certifications',x.id)}/><div className="field-grid"><Field label="Certificate Name" value={x.name} onChange={v=>updateList<Certification>('certifications',x.id,'name',v)}/><Field label="Organization" value={x.organization} onChange={v=>updateList<Certification>('certifications',x.id,'organization',v)}/><Field label="Year" value={x.year} onChange={v=>updateList<Certification>('certifications',x.id,'year',v)}/><Field label="Link" value={x.link} onChange={v=>updateList<Certification>('certifications',x.id,'link',v)}/></div></div>)}</Section>
        {(['achievements','languages'] as const).map(key=><Section key={key} title={key[0].toUpperCase()+key.slice(1)} onAdd={()=>addString(key)}><div className="tag-editor">{data[key].map((s,i)=><div className="inline-item" key={i}><input value={s} onChange={e=>setStringList(key,i,e.target.value)} placeholder={key==='achievements'?'Achievement bullet':'Language'}/><Remove onClick={()=>removeString(key,i)}/></div>)}</div></Section>)}
      </div>}
      <div className="preview-column"><div className="preview-label"><strong>Live Preview</strong><span>Saved locally</span></div><div ref={previewRef}><Preview data={data} template={template}/></div></div>
    </div>
  </section>
}
